### ISSUE TITLE
About the residual connection

### ISSUE THREAD

**Issue by FunkyKoki** [ZQPei/deep_joint_filter#2]
Thanks for your contribution, the code is very clean!

However, when I check your network implementation, I found that you did not use the residual connection.
So, is the residual connevtion necessary to the network design? Have you tried before?

**Comment by ZQPei** [comment]
Residual Connection is not mentioned in paper, so i ignored it in this implementation.
However, it is quite important for network training.

**Comment by FunkyKoki** [comment]
Thanks for  your answer. 
Actually, the authors published a better version [here](https://arxiv.org/pdf/1710.04200.pdf). And this version imports the Residual Connection. 
That's why I wonder whether you have tried the residual connection.
